"""
Personal AI Assistant
AI-based assistant system using OpenRouter API
"""

import os
import sys
from openai import OpenAI


class PersonalAssistant:
    """
    Main class for the personal AI assistant.
    Manages communication with the OpenRouter API.
    """
    
    def __init__(self, api_key: str):
        """
        Initializes the assistant with the API key.
        
        Args:
            api_key: OpenRouter API authentication key
        """
        self.client = OpenAI(
            api_key=api_key,
            base_url="https://openrouter.ai/api/v1"
        )
        
        self.model = "openai/gpt-4o-mini"
    
    def call_api(self, prompt: str, system_message: str = "You are a helpful assistant.") -> str:
        """
        Makes a call to the OpenRouter API to get an AI response.
        
        Args:
            prompt: The user's message/question
            system_message: System message that defines the AI's behavior
            
        Returns:
            The response generated by the AI
        """
        try:
            completion = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_message},
                    {"role": "user", "content": prompt}
                ],
                extra_headers={
                    "HTTP-Referer": "http://localhost:3000",
                    "X-Title": "Personal Assistant"
                }
            )
            
            return completion.choices[0].message.content
            
        except Exception as e:
            return f"Error calling API: {str(e)}"
    
    def draft_email(self):
        """
        Interactive assistant for generating professional emails.
        Collects user information and generates a complete email.
        """
        print("\n" + "="*50)
        print("=== Email Generator ===")
        print("="*50 + "\n")
        
        content = input("Describe what you need to say in the email: ")
        recipient = input("Who is the recipient? (e.g., 'my boss', 'a client'): ")
        tone = input("What tone? (e.g., 'formal', 'friendly', 'urgent'): ")
        
        prompt = f"""
        Please write a complete email with the following characteristics:
        
        Recipient: {recipient}
        Tone: {tone}
        Content: {content}
        
        The email should include:
        - Subject line (line with "Subject:")
        - Appropriate greeting
        - Well-structured email body
        - Professional closing
        
        Write in English.
        """
        
        system_message = "You are an expert in writing professional emails"
        
        print("\nGenerating email...\n")
        result = self.call_api(prompt, system_message)
        
        print("="*50)
        print(result)
        print("="*50 + "\n")
    
    def summarize_text(self):
        """
        Interactive assistant for summarizing long texts.
        Allows pasting multiple lines of text and generates a concise summary.
        """
        print("\n" + "="*50)
        print("=== Text Summarizer ===")
        print("="*50 + "\n")
        
        print("Paste your text (press Enter twice to finish):")
        
        lines = []
        while True:
            line = input()
            
            if line == "" and len(lines) > 0 and lines[-1] == "":
                break
            
            lines.append(line)
        
        text = "\n".join(lines[:-1])
        
        if not text.strip():
            print("\nError: No text was provided.\n")
            return
        
        prompt = f"Please provide a concise summary of the following text:\n\n{text}"
        
        system_message = "You are an expert in summarizing texts clearly and concisely"
        
        print("\nSummarizing...\n")
        result = self.call_api(prompt, system_message)
        
        print("="*50)
        print(result)
        print("="*50 + "\n")
    
    def generate_writing_prompt(self):
        """
        Creative writing prompt generator.
        Creates inspiring ideas based on genre and desired elements.
        """
        print("\n" + "="*50)
        print("=== Creative Writing Prompt Generator ===")
        print("="*50 + "\n")
        
        genre = input("What genre/theme do you want? (e.g., 'science fiction', 'romance', 'horror', 'fantasy'): ")
        
        if not genre.strip():
            genre = "any genre"
        
        element = input("Any specific element you want to include? (press Enter to skip): ")
        
        prompt = f"Generate 3 interesting and inspiring creative writing prompts for the genre: {genre}."
        
        if element.strip():
            prompt += f"\n\nMake sure to include the following element: {element}"
        
        prompt += "\n\nEach prompt should be unique, engaging, and spark the writer's imagination."
        
        system_message = "You are an experienced creative writer who generates inspiring prompts for stories"
        
        print("\nGenerating creative prompts...\n")
        result = self.call_api(prompt, system_message)
        
        print("="*50)
        print(result)
        print("="*50 + "\n")
    
    def run(self):
        """
        Main method that runs the assistant.
        Displays the interactive menu and manages navigation between features.
        """
        print("\n" + "="*50)
        print("Welcome to the Personal AI Assistant!")
        print("="*50 + "\n")
        
        while True:
            print("="*50)
            print("MAIN MENU")
            print("="*50)
            print("1. Email Generator")
            print("2. Text Summarizer")
            print("3. Creative Writing Prompt Generator")
            print("4. Exit")
            print("="*50)
            
            choice = input("Choose an option (1-4): ").strip()
            
            if choice == "1":
                self.draft_email()
                input("\nPress Enter to continue...")
                
            elif choice == "2":
                self.summarize_text()
                input("\nPress Enter to continue...")
                
            elif choice == "3":
                self.generate_writing_prompt()
                input("\nPress Enter to continue...")
                
            elif choice == "4":
                print("\nExiting assistant. Goodbye!")
                break
                
            else:
                print("\nInvalid option. Choose between 1 and 4.\n")


def main():
    """
    Main function that initializes and runs the assistant.
    Checks for the presence of the API key before starting.
    """
    api_key = os.environ.get("OPENROUTER_API_KEY")
    
    if not api_key and len(sys.argv) > 1:
        api_key = sys.argv[1]
    
    if not api_key:
        print("ERROR: API key not found!")
        print("\nTo use this assistant, you need to provide an OpenRouter API key.")
        print("\nOptions:")
        print("  1. Set as environment variable:")
        print("     export OPENROUTER_API_KEY='your-key-here'  (Linux/Mac)")
        print("     set OPENROUTER_API_KEY=your-key-here       (Windows)")
        print("\n  2. Pass as argument:")
        print("     python assistant.py your-key-here")
        print("\nGet your key at: https://openrouter.ai/keys")
        sys.exit(1)
    
    assistant = PersonalAssistant(api_key)
    assistant.run()


if __name__ == "__main__":
    main()
